services:
  server:
    container_name: space-jam-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    container_name: space-jam-redis
    image: "redis:latest"
    ports:
      - "6379:6379"